// Code generated by protoc-gen-go. DO NOT EDIT.
// source: class_schedule.proto

package class_schedule

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Week int32

const (
	Week_Zer  Week = 0
	Week_Mon  Week = 1
	Week_Tue  Week = 2
	Week_Wed  Week = 3
	Week_Thur Week = 4
	Week_Fri  Week = 5
	Week_Sat  Week = 6
	Week_Sun  Week = 7
)

var Week_name = map[int32]string{
	0: "Zer",
	1: "Mon",
	2: "Tue",
	3: "Wed",
	4: "Thur",
	5: "Fri",
	6: "Sat",
	7: "Sun",
}

var Week_value = map[string]int32{
	"Zer":  0,
	"Mon":  1,
	"Tue":  2,
	"Wed":  3,
	"Thur": 4,
	"Fri":  5,
	"Sat":  6,
	"Sun":  7,
}

func (x Week) String() string {
	return proto.EnumName(Week_name, int32(x))
}

func (Week) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d8ad3163d8148fd4, []int{0}
}

// GET /get_school
//支持哪些学校
type GetSchoolsResponse struct {
	StatusCode           int32    `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Schools              []string `protobuf:"bytes,3,rep,name=schools,proto3" json:"schools"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSchoolsResponse) Reset()         { *m = GetSchoolsResponse{} }
func (m *GetSchoolsResponse) String() string { return proto.CompactTextString(m) }
func (*GetSchoolsResponse) ProtoMessage()    {}
func (*GetSchoolsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8ad3163d8148fd4, []int{0}
}

func (m *GetSchoolsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSchoolsResponse.Unmarshal(m, b)
}
func (m *GetSchoolsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSchoolsResponse.Marshal(b, m, deterministic)
}
func (m *GetSchoolsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSchoolsResponse.Merge(m, src)
}
func (m *GetSchoolsResponse) XXX_Size() int {
	return xxx_messageInfo_GetSchoolsResponse.Size(m)
}
func (m *GetSchoolsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSchoolsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSchoolsResponse proto.InternalMessageInfo

func (m *GetSchoolsResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *GetSchoolsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetSchoolsResponse) GetSchools() []string {
	if m != nil {
		return m.Schools
	}
	return nil
}

// POST /set_school
//设置自己的学校
type SetSchoolsRequest struct {
	SchoolName           string   `protobuf:"bytes,1,opt,name=school_name,json=schoolName,proto3" json:"school_name"`
	StuId                string   `protobuf:"bytes,2,opt,name=stu_id,json=stuId,proto3" json:"stu_id"`
	StuPassword          string   `protobuf:"bytes,3,opt,name=stu_password,json=stuPassword,proto3" json:"stu_password"`
	VerifyCode           string   `protobuf:"bytes,4,opt,name=verify_code,json=verifyCode,proto3" json:"verify_code"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetSchoolsRequest) Reset()         { *m = SetSchoolsRequest{} }
func (m *SetSchoolsRequest) String() string { return proto.CompactTextString(m) }
func (*SetSchoolsRequest) ProtoMessage()    {}
func (*SetSchoolsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8ad3163d8148fd4, []int{1}
}

func (m *SetSchoolsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetSchoolsRequest.Unmarshal(m, b)
}
func (m *SetSchoolsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetSchoolsRequest.Marshal(b, m, deterministic)
}
func (m *SetSchoolsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetSchoolsRequest.Merge(m, src)
}
func (m *SetSchoolsRequest) XXX_Size() int {
	return xxx_messageInfo_SetSchoolsRequest.Size(m)
}
func (m *SetSchoolsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetSchoolsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetSchoolsRequest proto.InternalMessageInfo

func (m *SetSchoolsRequest) GetSchoolName() string {
	if m != nil {
		return m.SchoolName
	}
	return ""
}

func (m *SetSchoolsRequest) GetStuId() string {
	if m != nil {
		return m.StuId
	}
	return ""
}

func (m *SetSchoolsRequest) GetStuPassword() string {
	if m != nil {
		return m.StuPassword
	}
	return ""
}

func (m *SetSchoolsRequest) GetVerifyCode() string {
	if m != nil {
		return m.VerifyCode
	}
	return ""
}

type SetSchoolsResponse struct {
	StatusCode           int32    `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	AlertMessage         string   `protobuf:"bytes,3,opt,name=alert_message,json=alertMessage,proto3" json:"alert_message"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetSchoolsResponse) Reset()         { *m = SetSchoolsResponse{} }
func (m *SetSchoolsResponse) String() string { return proto.CompactTextString(m) }
func (*SetSchoolsResponse) ProtoMessage()    {}
func (*SetSchoolsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8ad3163d8148fd4, []int{2}
}

func (m *SetSchoolsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetSchoolsResponse.Unmarshal(m, b)
}
func (m *SetSchoolsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetSchoolsResponse.Marshal(b, m, deterministic)
}
func (m *SetSchoolsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetSchoolsResponse.Merge(m, src)
}
func (m *SetSchoolsResponse) XXX_Size() int {
	return xxx_messageInfo_SetSchoolsResponse.Size(m)
}
func (m *SetSchoolsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetSchoolsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetSchoolsResponse proto.InternalMessageInfo

func (m *SetSchoolsResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *SetSchoolsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SetSchoolsResponse) GetAlertMessage() string {
	if m != nil {
		return m.AlertMessage
	}
	return ""
}

type Course struct {
	WeekNum              Week     `protobuf:"varint,1,opt,name=week_num,json=weekNum,proto3,enum=Week" json:"week_num"`
	ClassNum             int32    `protobuf:"varint,2,opt,name=class_num,json=classNum,proto3" json:"class_num"`
	CourseName           string   `protobuf:"bytes,3,opt,name=course_name,json=courseName,proto3" json:"course_name"`
	TeacherName          string   `protobuf:"bytes,4,opt,name=teacher_name,json=teacherName,proto3" json:"teacher_name"`
	Place                string   `protobuf:"bytes,5,opt,name=place,proto3" json:"place"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Course) Reset()         { *m = Course{} }
func (m *Course) String() string { return proto.CompactTextString(m) }
func (*Course) ProtoMessage()    {}
func (*Course) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8ad3163d8148fd4, []int{3}
}

func (m *Course) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Course.Unmarshal(m, b)
}
func (m *Course) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Course.Marshal(b, m, deterministic)
}
func (m *Course) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Course.Merge(m, src)
}
func (m *Course) XXX_Size() int {
	return xxx_messageInfo_Course.Size(m)
}
func (m *Course) XXX_DiscardUnknown() {
	xxx_messageInfo_Course.DiscardUnknown(m)
}

var xxx_messageInfo_Course proto.InternalMessageInfo

func (m *Course) GetWeekNum() Week {
	if m != nil {
		return m.WeekNum
	}
	return Week_Zer
}

func (m *Course) GetClassNum() int32 {
	if m != nil {
		return m.ClassNum
	}
	return 0
}

func (m *Course) GetCourseName() string {
	if m != nil {
		return m.CourseName
	}
	return ""
}

func (m *Course) GetTeacherName() string {
	if m != nil {
		return m.TeacherName
	}
	return ""
}

func (m *Course) GetPlace() string {
	if m != nil {
		return m.Place
	}
	return ""
}

type GetCurClassResponse struct {
	StatusCode           int32     `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code"`
	Message              string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	AlertMessage         string    `protobuf:"bytes,3,opt,name=alert_message,json=alertMessage,proto3" json:"alert_message"`
	SchoolName           string    `protobuf:"bytes,4,opt,name=school_name,json=schoolName,proto3" json:"school_name"`
	Week                 int32     `protobuf:"varint,5,opt,name=week,proto3" json:"week"`
	Courses              []*Course `protobuf:"bytes,6,rep,name=courses,proto3" json:"courses"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetCurClassResponse) Reset()         { *m = GetCurClassResponse{} }
func (m *GetCurClassResponse) String() string { return proto.CompactTextString(m) }
func (*GetCurClassResponse) ProtoMessage()    {}
func (*GetCurClassResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8ad3163d8148fd4, []int{4}
}

func (m *GetCurClassResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCurClassResponse.Unmarshal(m, b)
}
func (m *GetCurClassResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCurClassResponse.Marshal(b, m, deterministic)
}
func (m *GetCurClassResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCurClassResponse.Merge(m, src)
}
func (m *GetCurClassResponse) XXX_Size() int {
	return xxx_messageInfo_GetCurClassResponse.Size(m)
}
func (m *GetCurClassResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCurClassResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCurClassResponse proto.InternalMessageInfo

func (m *GetCurClassResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *GetCurClassResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetCurClassResponse) GetAlertMessage() string {
	if m != nil {
		return m.AlertMessage
	}
	return ""
}

func (m *GetCurClassResponse) GetSchoolName() string {
	if m != nil {
		return m.SchoolName
	}
	return ""
}

func (m *GetCurClassResponse) GetWeek() int32 {
	if m != nil {
		return m.Week
	}
	return 0
}

func (m *GetCurClassResponse) GetCourses() []*Course {
	if m != nil {
		return m.Courses
	}
	return nil
}

// GET /get_course/by_week
// 获取第week周的课程表
type GetCourseByWeekNumRequest struct {
	SchoolName           string   `protobuf:"bytes,1,opt,name=school_name,json=schoolName,proto3" json:"school_name"`
	Week                 int32    `protobuf:"varint,2,opt,name=week,proto3" json:"week"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCourseByWeekNumRequest) Reset()         { *m = GetCourseByWeekNumRequest{} }
func (m *GetCourseByWeekNumRequest) String() string { return proto.CompactTextString(m) }
func (*GetCourseByWeekNumRequest) ProtoMessage()    {}
func (*GetCourseByWeekNumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8ad3163d8148fd4, []int{5}
}

func (m *GetCourseByWeekNumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCourseByWeekNumRequest.Unmarshal(m, b)
}
func (m *GetCourseByWeekNumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCourseByWeekNumRequest.Marshal(b, m, deterministic)
}
func (m *GetCourseByWeekNumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCourseByWeekNumRequest.Merge(m, src)
}
func (m *GetCourseByWeekNumRequest) XXX_Size() int {
	return xxx_messageInfo_GetCourseByWeekNumRequest.Size(m)
}
func (m *GetCourseByWeekNumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCourseByWeekNumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCourseByWeekNumRequest proto.InternalMessageInfo

func (m *GetCourseByWeekNumRequest) GetSchoolName() string {
	if m != nil {
		return m.SchoolName
	}
	return ""
}

func (m *GetCourseByWeekNumRequest) GetWeek() int32 {
	if m != nil {
		return m.Week
	}
	return 0
}

type GetCourseByWeekNumResponse struct {
	StatusCode           int32     `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code"`
	Message              string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	AlertMessage         string    `protobuf:"bytes,3,opt,name=alert_message,json=alertMessage,proto3" json:"alert_message"`
	SchoolName           string    `protobuf:"bytes,4,opt,name=school_name,json=schoolName,proto3" json:"school_name"`
	Week                 int32     `protobuf:"varint,5,opt,name=week,proto3" json:"week"`
	Courses              []*Course `protobuf:"bytes,6,rep,name=courses,proto3" json:"courses"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetCourseByWeekNumResponse) Reset()         { *m = GetCourseByWeekNumResponse{} }
func (m *GetCourseByWeekNumResponse) String() string { return proto.CompactTextString(m) }
func (*GetCourseByWeekNumResponse) ProtoMessage()    {}
func (*GetCourseByWeekNumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8ad3163d8148fd4, []int{6}
}

func (m *GetCourseByWeekNumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCourseByWeekNumResponse.Unmarshal(m, b)
}
func (m *GetCourseByWeekNumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCourseByWeekNumResponse.Marshal(b, m, deterministic)
}
func (m *GetCourseByWeekNumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCourseByWeekNumResponse.Merge(m, src)
}
func (m *GetCourseByWeekNumResponse) XXX_Size() int {
	return xxx_messageInfo_GetCourseByWeekNumResponse.Size(m)
}
func (m *GetCourseByWeekNumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCourseByWeekNumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCourseByWeekNumResponse proto.InternalMessageInfo

func (m *GetCourseByWeekNumResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *GetCourseByWeekNumResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetCourseByWeekNumResponse) GetAlertMessage() string {
	if m != nil {
		return m.AlertMessage
	}
	return ""
}

func (m *GetCourseByWeekNumResponse) GetSchoolName() string {
	if m != nil {
		return m.SchoolName
	}
	return ""
}

func (m *GetCourseByWeekNumResponse) GetWeek() int32 {
	if m != nil {
		return m.Week
	}
	return 0
}

func (m *GetCourseByWeekNumResponse) GetCourses() []*Course {
	if m != nil {
		return m.Courses
	}
	return nil
}

type GetVerifyCodeRequest struct {
	SchoolName           string   `protobuf:"bytes,1,opt,name=school_name,json=schoolName,proto3" json:"school_name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVerifyCodeRequest) Reset()         { *m = GetVerifyCodeRequest{} }
func (m *GetVerifyCodeRequest) String() string { return proto.CompactTextString(m) }
func (*GetVerifyCodeRequest) ProtoMessage()    {}
func (*GetVerifyCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8ad3163d8148fd4, []int{7}
}

func (m *GetVerifyCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVerifyCodeRequest.Unmarshal(m, b)
}
func (m *GetVerifyCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVerifyCodeRequest.Marshal(b, m, deterministic)
}
func (m *GetVerifyCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVerifyCodeRequest.Merge(m, src)
}
func (m *GetVerifyCodeRequest) XXX_Size() int {
	return xxx_messageInfo_GetVerifyCodeRequest.Size(m)
}
func (m *GetVerifyCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVerifyCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVerifyCodeRequest proto.InternalMessageInfo

func (m *GetVerifyCodeRequest) GetSchoolName() string {
	if m != nil {
		return m.SchoolName
	}
	return ""
}

type GetVerifyCodeResponse struct {
	StatusCode           int32    `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVerifyCodeResponse) Reset()         { *m = GetVerifyCodeResponse{} }
func (m *GetVerifyCodeResponse) String() string { return proto.CompactTextString(m) }
func (*GetVerifyCodeResponse) ProtoMessage()    {}
func (*GetVerifyCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8ad3163d8148fd4, []int{8}
}

func (m *GetVerifyCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVerifyCodeResponse.Unmarshal(m, b)
}
func (m *GetVerifyCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVerifyCodeResponse.Marshal(b, m, deterministic)
}
func (m *GetVerifyCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVerifyCodeResponse.Merge(m, src)
}
func (m *GetVerifyCodeResponse) XXX_Size() int {
	return xxx_messageInfo_GetVerifyCodeResponse.Size(m)
}
func (m *GetVerifyCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVerifyCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVerifyCodeResponse proto.InternalMessageInfo

func (m *GetVerifyCodeResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *GetVerifyCodeResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetVerifyCodeResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type SetCurWeekRequest struct {
	Week                 int32    `protobuf:"varint,1,opt,name=week,proto3" json:"week"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetCurWeekRequest) Reset()         { *m = SetCurWeekRequest{} }
func (m *SetCurWeekRequest) String() string { return proto.CompactTextString(m) }
func (*SetCurWeekRequest) ProtoMessage()    {}
func (*SetCurWeekRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8ad3163d8148fd4, []int{9}
}

func (m *SetCurWeekRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetCurWeekRequest.Unmarshal(m, b)
}
func (m *SetCurWeekRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetCurWeekRequest.Marshal(b, m, deterministic)
}
func (m *SetCurWeekRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetCurWeekRequest.Merge(m, src)
}
func (m *SetCurWeekRequest) XXX_Size() int {
	return xxx_messageInfo_SetCurWeekRequest.Size(m)
}
func (m *SetCurWeekRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetCurWeekRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetCurWeekRequest proto.InternalMessageInfo

func (m *SetCurWeekRequest) GetWeek() int32 {
	if m != nil {
		return m.Week
	}
	return 0
}

type SetCurWeekResponse struct {
	StatusCode           int32    `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetCurWeekResponse) Reset()         { *m = SetCurWeekResponse{} }
func (m *SetCurWeekResponse) String() string { return proto.CompactTextString(m) }
func (*SetCurWeekResponse) ProtoMessage()    {}
func (*SetCurWeekResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8ad3163d8148fd4, []int{10}
}

func (m *SetCurWeekResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetCurWeekResponse.Unmarshal(m, b)
}
func (m *SetCurWeekResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetCurWeekResponse.Marshal(b, m, deterministic)
}
func (m *SetCurWeekResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetCurWeekResponse.Merge(m, src)
}
func (m *SetCurWeekResponse) XXX_Size() int {
	return xxx_messageInfo_SetCurWeekResponse.Size(m)
}
func (m *SetCurWeekResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetCurWeekResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetCurWeekResponse proto.InternalMessageInfo

func (m *SetCurWeekResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *SetCurWeekResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("Week", Week_name, Week_value)
	proto.RegisterType((*GetSchoolsResponse)(nil), "GetSchoolsResponse")
	proto.RegisterType((*SetSchoolsRequest)(nil), "SetSchoolsRequest")
	proto.RegisterType((*SetSchoolsResponse)(nil), "SetSchoolsResponse")
	proto.RegisterType((*Course)(nil), "Course")
	proto.RegisterType((*GetCurClassResponse)(nil), "GetCurClassResponse")
	proto.RegisterType((*GetCourseByWeekNumRequest)(nil), "GetCourseByWeekNumRequest")
	proto.RegisterType((*GetCourseByWeekNumResponse)(nil), "GetCourseByWeekNumResponse")
	proto.RegisterType((*GetVerifyCodeRequest)(nil), "GetVerifyCodeRequest")
	proto.RegisterType((*GetVerifyCodeResponse)(nil), "GetVerifyCodeResponse")
	proto.RegisterType((*SetCurWeekRequest)(nil), "SetCurWeekRequest")
	proto.RegisterType((*SetCurWeekResponse)(nil), "SetCurWeekResponse")
}

func init() { proto.RegisterFile("class_schedule.proto", fileDescriptor_d8ad3163d8148fd4) }

var fileDescriptor_d8ad3163d8148fd4 = []byte{
	// 520 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xf1, 0x5f, 0x33, 0x0e, 0xc8, 0x2c, 0xa9, 0x64, 0xe0, 0x50, 0xc7, 0x1c, 0x88, 0x38,
	0xe4, 0x50, 0x0e, 0xdc, 0xb1, 0x44, 0xc4, 0xa1, 0x3f, 0x72, 0x2a, 0x22, 0x71, 0xb1, 0x16, 0x7b,
	0x20, 0x51, 0x6d, 0x6f, 0xd8, 0x1f, 0xaa, 0x3e, 0x05, 0xcf, 0xc0, 0x03, 0x71, 0xe3, 0x81, 0xd0,
	0xee, 0xda, 0xa5, 0x2a, 0x1c, 0x2a, 0x15, 0x21, 0x71, 0x9b, 0xf9, 0x66, 0x3c, 0xdf, 0x7c, 0x9f,
	0x77, 0x17, 0xa6, 0x55, 0x43, 0x85, 0x28, 0x45, 0xb5, 0xc1, 0x5a, 0x35, 0xb8, 0xd8, 0x71, 0x26,
	0x59, 0xb6, 0x05, 0xb2, 0x44, 0xb9, 0xaa, 0x36, 0x8c, 0x35, 0xa2, 0x40, 0xb1, 0x63, 0x9d, 0x40,
	0x72, 0x00, 0x91, 0x90, 0x54, 0x2a, 0x51, 0x56, 0xac, 0xc6, 0xc4, 0x49, 0x9d, 0xb9, 0x5f, 0x80,
	0x85, 0x72, 0x56, 0x23, 0x49, 0x20, 0x6c, 0x51, 0x08, 0xfa, 0x09, 0x93, 0x51, 0xea, 0xcc, 0xc7,
	0xc5, 0x90, 0xea, 0x8a, 0xb0, 0xd3, 0x12, 0x37, 0x75, 0x75, 0xa5, 0x4f, 0xb3, 0xaf, 0x0e, 0x3c,
	0x5c, 0x5d, 0xe3, 0xfa, 0xac, 0x50, 0x48, 0x43, 0x65, 0x90, 0xb2, 0xa3, 0xad, 0xa5, 0x1a, 0x17,
	0x60, 0xa1, 0x63, 0xda, 0x22, 0xd9, 0x87, 0x40, 0x48, 0x55, 0x6e, 0xeb, 0x9e, 0xc9, 0x17, 0x52,
	0xbd, 0xad, 0xc9, 0x0c, 0x26, 0x1a, 0xde, 0x51, 0x21, 0x2e, 0x18, 0xaf, 0x13, 0xd7, 0x14, 0x23,
	0x21, 0xd5, 0x69, 0x0f, 0xe9, 0xd1, 0x5f, 0x90, 0x6f, 0x3f, 0x5e, 0x5a, 0x15, 0x9e, 0x1d, 0x6d,
	0x21, 0xad, 0x22, 0x93, 0x40, 0x56, 0x7f, 0x55, 0xfc, 0x33, 0xb8, 0x4f, 0x1b, 0xe4, 0xb2, 0x1c,
	0xea, 0x76, 0xab, 0x89, 0x01, 0x8f, 0x2c, 0x96, 0x7d, 0x73, 0x20, 0xc8, 0x99, 0xe2, 0x02, 0x49,
	0x0a, 0x7b, 0x17, 0x88, 0xe7, 0x65, 0xa7, 0x5a, 0xc3, 0xf3, 0xe0, 0xd0, 0x5f, 0xac, 0x11, 0xcf,
	0x8b, 0x50, 0xc3, 0xc7, 0xaa, 0x25, 0x4f, 0x61, 0x6c, 0xff, 0x9b, 0x6e, 0x19, 0x99, 0x55, 0xf6,
	0x0c, 0xa0, 0x8b, 0x07, 0x10, 0x55, 0x66, 0x90, 0xf5, 0xce, 0x92, 0x81, 0x85, 0x8c, 0x77, 0x33,
	0x98, 0x48, 0xa4, 0xd5, 0x06, 0xb9, 0xed, 0xb0, 0x16, 0x44, 0x3d, 0x66, 0x5a, 0xa6, 0xe0, 0xef,
	0x1a, 0x5a, 0x61, 0xe2, 0x5b, 0x77, 0x4d, 0x92, 0x7d, 0x77, 0xe0, 0xd1, 0x12, 0x65, 0xae, 0x78,
	0xae, 0xc9, 0xfe, 0x95, 0x37, 0x37, 0x4f, 0x83, 0xf7, 0xdb, 0x69, 0x20, 0xe0, 0x69, 0x6b, 0xcc,
	0xb6, 0x7e, 0x61, 0x62, 0x32, 0x83, 0xd0, 0x6a, 0x16, 0x49, 0x90, 0xba, 0xf3, 0xe8, 0x30, 0x5c,
	0x58, 0x7f, 0x8b, 0x01, 0xcf, 0x4e, 0xe1, 0xb1, 0x96, 0x63, 0xb2, 0xd7, 0x97, 0x6b, 0x6b, 0xee,
	0xad, 0x8f, 0xe0, 0x40, 0x3a, 0xfa, 0x45, 0x9a, 0xfd, 0x70, 0xe0, 0xc9, 0x9f, 0x46, 0xfe, 0xe7,
	0x46, 0xbd, 0x82, 0xe9, 0x12, 0xe5, 0xbb, 0xab, 0x3b, 0x72, 0x5b, 0x8f, 0xb2, 0x1a, 0xf6, 0x6f,
	0x7c, 0x78, 0x77, 0x27, 0x62, 0x70, 0x15, 0x6f, 0x7a, 0xfd, 0x3a, 0xcc, 0x9e, 0x9b, 0x27, 0x24,
	0x57, 0xdc, 0xdc, 0x92, 0x7e, 0xb7, 0x41, 0xaa, 0x73, 0xed, 0xf7, 0x9c, 0x98, 0xab, 0x7d, 0xd5,
	0x78, 0xe7, 0x5d, 0x5e, 0x9c, 0x80, 0xa7, 0x47, 0x91, 0x10, 0xdc, 0xf7, 0xc8, 0xe3, 0x7b, 0x3a,
	0x38, 0x62, 0x5d, 0xec, 0xe8, 0xe0, 0x4c, 0x61, 0x3c, 0xd2, 0xc1, 0x1a, 0xeb, 0xd8, 0x25, 0x7b,
	0xe0, 0x9d, 0x6d, 0x14, 0x8f, 0x3d, 0x0d, 0xbd, 0xe1, 0xdb, 0xd8, 0xd7, 0xc1, 0x8a, 0xca, 0x38,
	0x30, 0x81, 0xea, 0xe2, 0xf0, 0x43, 0x60, 0x1e, 0xe0, 0x97, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x88, 0xc7, 0x7e, 0x97, 0x98, 0x05, 0x00, 0x00,
}
