// Code generated by protoc-gen-go. DO NOT EDIT.
// source: class_schedule.proto

package class_schedule

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Week int32

const (
	Week_Mon  Week = 0
	Week_Tue  Week = 1
	Week_Wed  Week = 2
	Week_Thur Week = 3
	Week_Fri  Week = 4
	Week_Sat  Week = 5
	Week_Sun  Week = 6
)

var Week_name = map[int32]string{
	0: "Mon",
	1: "Tue",
	2: "Wed",
	3: "Thur",
	4: "Fri",
	5: "Sat",
	6: "Sun",
}

var Week_value = map[string]int32{
	"Mon":  0,
	"Tue":  1,
	"Wed":  2,
	"Thur": 3,
	"Fri":  4,
	"Sat":  5,
	"Sun":  6,
}

func (x Week) String() string {
	return proto.EnumName(Week_name, int32(x))
}

func (Week) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d8ad3163d8148fd4, []int{0}
}

// path = "/get_school"
//支持哪些学校
type GetSchoolsResponse struct {
	StatusCode           int32    `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Schools              []string `protobuf:"bytes,3,rep,name=schools,proto3" json:"schools,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSchoolsResponse) Reset()         { *m = GetSchoolsResponse{} }
func (m *GetSchoolsResponse) String() string { return proto.CompactTextString(m) }
func (*GetSchoolsResponse) ProtoMessage()    {}
func (*GetSchoolsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8ad3163d8148fd4, []int{0}
}

func (m *GetSchoolsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSchoolsResponse.Unmarshal(m, b)
}
func (m *GetSchoolsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSchoolsResponse.Marshal(b, m, deterministic)
}
func (m *GetSchoolsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSchoolsResponse.Merge(m, src)
}
func (m *GetSchoolsResponse) XXX_Size() int {
	return xxx_messageInfo_GetSchoolsResponse.Size(m)
}
func (m *GetSchoolsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSchoolsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSchoolsResponse proto.InternalMessageInfo

func (m *GetSchoolsResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *GetSchoolsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetSchoolsResponse) GetSchools() []string {
	if m != nil {
		return m.Schools
	}
	return nil
}

// path = "/set_school"
//设置自己的学校
type SetSchoolsRequest struct {
	SchoolName           string   `protobuf:"bytes,1,opt,name=school_name,json=schoolName,proto3" json:"school_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetSchoolsRequest) Reset()         { *m = SetSchoolsRequest{} }
func (m *SetSchoolsRequest) String() string { return proto.CompactTextString(m) }
func (*SetSchoolsRequest) ProtoMessage()    {}
func (*SetSchoolsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8ad3163d8148fd4, []int{1}
}

func (m *SetSchoolsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetSchoolsRequest.Unmarshal(m, b)
}
func (m *SetSchoolsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetSchoolsRequest.Marshal(b, m, deterministic)
}
func (m *SetSchoolsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetSchoolsRequest.Merge(m, src)
}
func (m *SetSchoolsRequest) XXX_Size() int {
	return xxx_messageInfo_SetSchoolsRequest.Size(m)
}
func (m *SetSchoolsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetSchoolsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetSchoolsRequest proto.InternalMessageInfo

func (m *SetSchoolsRequest) GetSchoolName() string {
	if m != nil {
		return m.SchoolName
	}
	return ""
}

type SetSchoolsResponse struct {
	StatusCode           int32    `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AlertMessage         string   `protobuf:"bytes,3,opt,name=alert_message,json=alertMessage,proto3" json:"alert_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetSchoolsResponse) Reset()         { *m = SetSchoolsResponse{} }
func (m *SetSchoolsResponse) String() string { return proto.CompactTextString(m) }
func (*SetSchoolsResponse) ProtoMessage()    {}
func (*SetSchoolsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8ad3163d8148fd4, []int{2}
}

func (m *SetSchoolsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetSchoolsResponse.Unmarshal(m, b)
}
func (m *SetSchoolsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetSchoolsResponse.Marshal(b, m, deterministic)
}
func (m *SetSchoolsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetSchoolsResponse.Merge(m, src)
}
func (m *SetSchoolsResponse) XXX_Size() int {
	return xxx_messageInfo_SetSchoolsResponse.Size(m)
}
func (m *SetSchoolsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetSchoolsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetSchoolsResponse proto.InternalMessageInfo

func (m *SetSchoolsResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *SetSchoolsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SetSchoolsResponse) GetAlertMessage() string {
	if m != nil {
		return m.AlertMessage
	}
	return ""
}

type Course struct {
	WeekNum              Week     `protobuf:"varint,1,opt,name=week_num,json=weekNum,proto3,enum=Week" json:"week_num,omitempty"`
	ClassNum             int32    `protobuf:"varint,2,opt,name=class_num,json=classNum,proto3" json:"class_num,omitempty"`
	CourseName           string   `protobuf:"bytes,3,opt,name=course_name,json=courseName,proto3" json:"course_name,omitempty"`
	TeacherName          string   `protobuf:"bytes,4,opt,name=teacher_name,json=teacherName,proto3" json:"teacher_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Course) Reset()         { *m = Course{} }
func (m *Course) String() string { return proto.CompactTextString(m) }
func (*Course) ProtoMessage()    {}
func (*Course) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8ad3163d8148fd4, []int{3}
}

func (m *Course) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Course.Unmarshal(m, b)
}
func (m *Course) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Course.Marshal(b, m, deterministic)
}
func (m *Course) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Course.Merge(m, src)
}
func (m *Course) XXX_Size() int {
	return xxx_messageInfo_Course.Size(m)
}
func (m *Course) XXX_DiscardUnknown() {
	xxx_messageInfo_Course.DiscardUnknown(m)
}

var xxx_messageInfo_Course proto.InternalMessageInfo

func (m *Course) GetWeekNum() Week {
	if m != nil {
		return m.WeekNum
	}
	return Week_Mon
}

func (m *Course) GetClassNum() int32 {
	if m != nil {
		return m.ClassNum
	}
	return 0
}

func (m *Course) GetCourseName() string {
	if m != nil {
		return m.CourseName
	}
	return ""
}

func (m *Course) GetTeacherName() string {
	if m != nil {
		return m.TeacherName
	}
	return ""
}

type GetCurClassResponse struct {
	StatusCode           int32     `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message              string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AlertMessage         string    `protobuf:"bytes,3,opt,name=alert_message,json=alertMessage,proto3" json:"alert_message,omitempty"`
	SchoolName           string    `protobuf:"bytes,4,opt,name=school_name,json=schoolName,proto3" json:"school_name,omitempty"`
	Week                 int32     `protobuf:"varint,5,opt,name=week,proto3" json:"week,omitempty"`
	Courses              []*Course `protobuf:"bytes,6,rep,name=courses,proto3" json:"courses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetCurClassResponse) Reset()         { *m = GetCurClassResponse{} }
func (m *GetCurClassResponse) String() string { return proto.CompactTextString(m) }
func (*GetCurClassResponse) ProtoMessage()    {}
func (*GetCurClassResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8ad3163d8148fd4, []int{4}
}

func (m *GetCurClassResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCurClassResponse.Unmarshal(m, b)
}
func (m *GetCurClassResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCurClassResponse.Marshal(b, m, deterministic)
}
func (m *GetCurClassResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCurClassResponse.Merge(m, src)
}
func (m *GetCurClassResponse) XXX_Size() int {
	return xxx_messageInfo_GetCurClassResponse.Size(m)
}
func (m *GetCurClassResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCurClassResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCurClassResponse proto.InternalMessageInfo

func (m *GetCurClassResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *GetCurClassResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetCurClassResponse) GetAlertMessage() string {
	if m != nil {
		return m.AlertMessage
	}
	return ""
}

func (m *GetCurClassResponse) GetSchoolName() string {
	if m != nil {
		return m.SchoolName
	}
	return ""
}

func (m *GetCurClassResponse) GetWeek() int32 {
	if m != nil {
		return m.Week
	}
	return 0
}

func (m *GetCurClassResponse) GetCourses() []*Course {
	if m != nil {
		return m.Courses
	}
	return nil
}

// path = "/get_course/by_week"
// 获取第week周的课程表
type GetCourseByWeekNumRequest struct {
	SchoolName           string   `protobuf:"bytes,1,opt,name=school_name,json=schoolName,proto3" json:"school_name,omitempty"`
	Week                 int32    `protobuf:"varint,2,opt,name=week,proto3" json:"week,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCourseByWeekNumRequest) Reset()         { *m = GetCourseByWeekNumRequest{} }
func (m *GetCourseByWeekNumRequest) String() string { return proto.CompactTextString(m) }
func (*GetCourseByWeekNumRequest) ProtoMessage()    {}
func (*GetCourseByWeekNumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8ad3163d8148fd4, []int{5}
}

func (m *GetCourseByWeekNumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCourseByWeekNumRequest.Unmarshal(m, b)
}
func (m *GetCourseByWeekNumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCourseByWeekNumRequest.Marshal(b, m, deterministic)
}
func (m *GetCourseByWeekNumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCourseByWeekNumRequest.Merge(m, src)
}
func (m *GetCourseByWeekNumRequest) XXX_Size() int {
	return xxx_messageInfo_GetCourseByWeekNumRequest.Size(m)
}
func (m *GetCourseByWeekNumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCourseByWeekNumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCourseByWeekNumRequest proto.InternalMessageInfo

func (m *GetCourseByWeekNumRequest) GetSchoolName() string {
	if m != nil {
		return m.SchoolName
	}
	return ""
}

func (m *GetCourseByWeekNumRequest) GetWeek() int32 {
	if m != nil {
		return m.Week
	}
	return 0
}

type GetCourseByWeekNumResponse struct {
	StatusCode           int32     `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message              string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AlertMessage         string    `protobuf:"bytes,3,opt,name=alert_message,json=alertMessage,proto3" json:"alert_message,omitempty"`
	SchoolName           string    `protobuf:"bytes,4,opt,name=school_name,json=schoolName,proto3" json:"school_name,omitempty"`
	Week                 int32     `protobuf:"varint,5,opt,name=week,proto3" json:"week,omitempty"`
	Courses              []*Course `protobuf:"bytes,6,rep,name=courses,proto3" json:"courses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetCourseByWeekNumResponse) Reset()         { *m = GetCourseByWeekNumResponse{} }
func (m *GetCourseByWeekNumResponse) String() string { return proto.CompactTextString(m) }
func (*GetCourseByWeekNumResponse) ProtoMessage()    {}
func (*GetCourseByWeekNumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8ad3163d8148fd4, []int{6}
}

func (m *GetCourseByWeekNumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCourseByWeekNumResponse.Unmarshal(m, b)
}
func (m *GetCourseByWeekNumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCourseByWeekNumResponse.Marshal(b, m, deterministic)
}
func (m *GetCourseByWeekNumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCourseByWeekNumResponse.Merge(m, src)
}
func (m *GetCourseByWeekNumResponse) XXX_Size() int {
	return xxx_messageInfo_GetCourseByWeekNumResponse.Size(m)
}
func (m *GetCourseByWeekNumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCourseByWeekNumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCourseByWeekNumResponse proto.InternalMessageInfo

func (m *GetCourseByWeekNumResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *GetCourseByWeekNumResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetCourseByWeekNumResponse) GetAlertMessage() string {
	if m != nil {
		return m.AlertMessage
	}
	return ""
}

func (m *GetCourseByWeekNumResponse) GetSchoolName() string {
	if m != nil {
		return m.SchoolName
	}
	return ""
}

func (m *GetCourseByWeekNumResponse) GetWeek() int32 {
	if m != nil {
		return m.Week
	}
	return 0
}

func (m *GetCourseByWeekNumResponse) GetCourses() []*Course {
	if m != nil {
		return m.Courses
	}
	return nil
}

func init() {
	proto.RegisterEnum("Week", Week_name, Week_value)
	proto.RegisterType((*GetSchoolsResponse)(nil), "GetSchoolsResponse")
	proto.RegisterType((*SetSchoolsRequest)(nil), "SetSchoolsRequest")
	proto.RegisterType((*SetSchoolsResponse)(nil), "SetSchoolsResponse")
	proto.RegisterType((*Course)(nil), "Course")
	proto.RegisterType((*GetCurClassResponse)(nil), "GetCurClassResponse")
	proto.RegisterType((*GetCourseByWeekNumRequest)(nil), "GetCourseByWeekNumRequest")
	proto.RegisterType((*GetCourseByWeekNumResponse)(nil), "GetCourseByWeekNumResponse")
}

func init() { proto.RegisterFile("class_schedule.proto", fileDescriptor_d8ad3163d8148fd4) }

var fileDescriptor_d8ad3163d8148fd4 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x93, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0xc9, 0xff, 0x76, 0x52, 0x50, 0x30, 0x1c, 0x02, 0x1c, 0x9a, 0x86, 0x4b, 0xc5, 0xa1,
	0x87, 0xc2, 0x13, 0x10, 0xa9, 0x3d, 0xb5, 0x42, 0x49, 0xa5, 0x1e, 0x23, 0x93, 0x8c, 0x48, 0xd5,
	0x24, 0x2e, 0xb1, 0x2d, 0xc4, 0x33, 0xf0, 0x6c, 0xdc, 0x78, 0x20, 0x64, 0xbb, 0xdd, 0x5d, 0x55,
	0x7b, 0xd8, 0xc3, 0x6a, 0xa5, 0xbd, 0x8d, 0x7f, 0x33, 0x9a, 0xcf, 0xdf, 0xe7, 0x04, 0xde, 0x56,
	0x2d, 0xe5, 0xbc, 0xe4, 0x55, 0x83, 0xb5, 0x6c, 0x71, 0x71, 0x1a, 0x98, 0x60, 0xe9, 0x01, 0xc8,
	0x1a, 0x45, 0x51, 0x35, 0x8c, 0xb5, 0x3c, 0x47, 0x7e, 0x62, 0x3d, 0x47, 0x32, 0x85, 0x90, 0x0b,
	0x2a, 0x24, 0x2f, 0x2b, 0x56, 0x63, 0x6c, 0x25, 0xd6, 0xdc, 0xcb, 0xc1, 0xa0, 0x8c, 0xd5, 0x48,
	0x62, 0x08, 0x3a, 0xe4, 0x9c, 0xfe, 0xc0, 0xd8, 0x4e, 0xac, 0xf9, 0x38, 0xbf, 0x1c, 0x55, 0x87,
	0x9b, 0x6d, 0xb1, 0x93, 0x38, 0xaa, 0x73, 0x3e, 0xa6, 0x5f, 0xe0, 0x75, 0x71, 0x47, 0xea, 0xa7,
	0x44, 0x2e, 0xb4, 0x92, 0x26, 0x65, 0x4f, 0x3b, 0xa3, 0x34, 0xce, 0xc1, 0xa0, 0x2d, 0xed, 0x30,
	0x15, 0x40, 0x8a, 0x47, 0xbd, 0xe0, 0x47, 0x78, 0x49, 0x5b, 0x1c, 0x44, 0x79, 0xe9, 0x3b, 0xba,
	0x3f, 0xd1, 0x70, 0x63, 0x58, 0xfa, 0xc7, 0x02, 0x3f, 0x63, 0x72, 0xe0, 0x48, 0x12, 0x18, 0xfd,
	0x42, 0x3c, 0x96, 0xbd, 0xec, 0xb4, 0xce, 0xab, 0xa5, 0xb7, 0xd8, 0x23, 0x1e, 0xf3, 0x40, 0xe1,
	0xad, 0xec, 0xc8, 0x07, 0x18, 0x9b, 0x6c, 0xd5, 0x88, 0xad, 0xaf, 0x32, 0xd2, 0x40, 0x35, 0xa7,
	0x10, 0x56, 0x7a, 0x91, 0x31, 0x68, 0xc4, 0xc0, 0x20, 0x65, 0x90, 0xcc, 0x60, 0x22, 0x90, 0x56,
	0x0d, 0x0e, 0x66, 0xc2, 0xd5, 0x13, 0xe1, 0x99, 0xe9, 0x0c, 0xfe, 0x5a, 0xf0, 0x66, 0x8d, 0x22,
	0x93, 0x43, 0xa6, 0xd6, 0x3e, 0x55, 0x0a, 0xd7, 0x8f, 0xe3, 0x5e, 0x3f, 0x0e, 0x21, 0xe0, 0xaa,
	0x10, 0x62, 0x4f, 0x2b, 0xeb, 0x9a, 0xcc, 0x20, 0x30, 0xee, 0x78, 0xec, 0x27, 0xce, 0x3c, 0x5c,
	0x06, 0x0b, 0x93, 0x64, 0x7e, 0xe1, 0xe9, 0x37, 0x78, 0xa7, 0xec, 0xe8, 0xd3, 0xd7, 0xdf, 0x7b,
	0x13, 0xe3, 0x43, 0xbf, 0x88, 0x1b, 0x51, 0xfb, 0x56, 0x34, 0xfd, 0x67, 0xc1, 0xfb, 0xfb, 0x56,
	0x3e, 0xef, 0xa0, 0x3e, 0xad, 0xc0, 0x55, 0x56, 0x48, 0x00, 0xce, 0x86, 0xf5, 0xd1, 0x0b, 0x55,
	0xec, 0x24, 0x46, 0x96, 0x2a, 0xf6, 0x58, 0x47, 0x36, 0x19, 0x81, 0xbb, 0x6b, 0xe4, 0x10, 0x39,
	0x0a, 0xad, 0x86, 0x43, 0xe4, 0xaa, 0xa2, 0xa0, 0x22, 0xf2, 0x74, 0x21, 0xfb, 0xc8, 0xff, 0xee,
	0xeb, 0x9f, 0xfd, 0xf3, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x9d, 0xd0, 0xe5, 0x04, 0x04,
	0x00, 0x00,
}
