// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//创建消息
// POST /create/message
type CreateMessageRequest struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Uris                 []string `protobuf:"bytes,2,rep,name=uris,proto3" json:"uris,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMessageRequest) Reset()         { *m = CreateMessageRequest{} }
func (m *CreateMessageRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMessageRequest) ProtoMessage()    {}
func (*CreateMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *CreateMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMessageRequest.Unmarshal(m, b)
}
func (m *CreateMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMessageRequest.Marshal(b, m, deterministic)
}
func (m *CreateMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMessageRequest.Merge(m, src)
}
func (m *CreateMessageRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMessageRequest.Size(m)
}
func (m *CreateMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMessageRequest proto.InternalMessageInfo

func (m *CreateMessageRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CreateMessageRequest) GetUris() []string {
	if m != nil {
		return m.Uris
	}
	return nil
}

type CreateMessageResponse struct {
	StatusCode           int32    `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MessageId            int64    `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Uris                 []string `protobuf:"bytes,5,rep,name=uris,proto3" json:"uris,omitempty"`
	CreateTime           int64    `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMessageResponse) Reset()         { *m = CreateMessageResponse{} }
func (m *CreateMessageResponse) String() string { return proto.CompactTextString(m) }
func (*CreateMessageResponse) ProtoMessage()    {}
func (*CreateMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *CreateMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMessageResponse.Unmarshal(m, b)
}
func (m *CreateMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMessageResponse.Marshal(b, m, deterministic)
}
func (m *CreateMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMessageResponse.Merge(m, src)
}
func (m *CreateMessageResponse) XXX_Size() int {
	return xxx_messageInfo_CreateMessageResponse.Size(m)
}
func (m *CreateMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMessageResponse proto.InternalMessageInfo

func (m *CreateMessageResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *CreateMessageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateMessageResponse) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *CreateMessageResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CreateMessageResponse) GetUris() []string {
	if m != nil {
		return m.Uris
	}
	return nil
}

func (m *CreateMessageResponse) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

// GET /get/self_message
type GetSelfMessageRequest struct {
	Index                int64    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	MessageType          int32    `protobuf:"varint,3,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSelfMessageRequest) Reset()         { *m = GetSelfMessageRequest{} }
func (m *GetSelfMessageRequest) String() string { return proto.CompactTextString(m) }
func (*GetSelfMessageRequest) ProtoMessage()    {}
func (*GetSelfMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *GetSelfMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSelfMessageRequest.Unmarshal(m, b)
}
func (m *GetSelfMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSelfMessageRequest.Marshal(b, m, deterministic)
}
func (m *GetSelfMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSelfMessageRequest.Merge(m, src)
}
func (m *GetSelfMessageRequest) XXX_Size() int {
	return xxx_messageInfo_GetSelfMessageRequest.Size(m)
}
func (m *GetSelfMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSelfMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSelfMessageRequest proto.InternalMessageInfo

func (m *GetSelfMessageRequest) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *GetSelfMessageRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetSelfMessageRequest) GetMessageType() int32 {
	if m != nil {
		return m.MessageType
	}
	return 0
}

type MessageInfo struct {
	MessageId            int64    `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Urls                 []string `protobuf:"bytes,3,rep,name=urls,proto3" json:"urls,omitempty"`
	CreateTime           int64    `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageInfo) Reset()         { *m = MessageInfo{} }
func (m *MessageInfo) String() string { return proto.CompactTextString(m) }
func (*MessageInfo) ProtoMessage()    {}
func (*MessageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *MessageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageInfo.Unmarshal(m, b)
}
func (m *MessageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageInfo.Marshal(b, m, deterministic)
}
func (m *MessageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageInfo.Merge(m, src)
}
func (m *MessageInfo) XXX_Size() int {
	return xxx_messageInfo_MessageInfo.Size(m)
}
func (m *MessageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MessageInfo proto.InternalMessageInfo

func (m *MessageInfo) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *MessageInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MessageInfo) GetUrls() []string {
	if m != nil {
		return m.Urls
	}
	return nil
}

func (m *MessageInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type GetSelfMessageResonse struct {
	StatusCode           int32          `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message              string         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MessageInfos         []*MessageInfo `protobuf:"bytes,3,rep,name=message_infos,json=messageInfos,proto3" json:"message_infos,omitempty"`
	Count                int64          `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	HasMore              bool           `protobuf:"varint,5,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetSelfMessageResonse) Reset()         { *m = GetSelfMessageResonse{} }
func (m *GetSelfMessageResonse) String() string { return proto.CompactTextString(m) }
func (*GetSelfMessageResonse) ProtoMessage()    {}
func (*GetSelfMessageResonse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *GetSelfMessageResonse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSelfMessageResonse.Unmarshal(m, b)
}
func (m *GetSelfMessageResonse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSelfMessageResonse.Marshal(b, m, deterministic)
}
func (m *GetSelfMessageResonse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSelfMessageResonse.Merge(m, src)
}
func (m *GetSelfMessageResonse) XXX_Size() int {
	return xxx_messageInfo_GetSelfMessageResonse.Size(m)
}
func (m *GetSelfMessageResonse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSelfMessageResonse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSelfMessageResonse proto.InternalMessageInfo

func (m *GetSelfMessageResonse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *GetSelfMessageResonse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetSelfMessageResonse) GetMessageInfos() []*MessageInfo {
	if m != nil {
		return m.MessageInfos
	}
	return nil
}

func (m *GetSelfMessageResonse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetSelfMessageResonse) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

func init() {
	proto.RegisterType((*CreateMessageRequest)(nil), "CreateMessageRequest")
	proto.RegisterType((*CreateMessageResponse)(nil), "CreateMessageResponse")
	proto.RegisterType((*GetSelfMessageRequest)(nil), "GetSelfMessageRequest")
	proto.RegisterType((*MessageInfo)(nil), "MessageInfo")
	proto.RegisterType((*GetSelfMessageResonse)(nil), "GetSelfMessageResonse")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x4f, 0x4f, 0x83, 0x40,
	0x10, 0xc5, 0x43, 0x81, 0xfe, 0x19, 0xea, 0x85, 0xb4, 0xc9, 0x7a, 0x30, 0x22, 0x27, 0x4e, 0x4d,
	0xd4, 0x8f, 0x50, 0x13, 0xd3, 0x43, 0x2f, 0x6b, 0xef, 0x04, 0x61, 0xb0, 0x24, 0x65, 0x17, 0x99,
	0x25, 0xb1, 0xf1, 0x7b, 0x79, 0xf6, 0xa3, 0x19, 0x76, 0xc1, 0x36, 0x6d, 0xe3, 0xc5, 0xdb, 0xbe,
	0x77, 0x98, 0xf9, 0xbd, 0xb7, 0x03, 0x57, 0x25, 0x12, 0x25, 0x6f, 0xb8, 0xa8, 0x6a, 0xa9, 0x64,
	0xf8, 0x04, 0xb3, 0x65, 0x8d, 0x89, 0xc2, 0xb5, 0xb1, 0x39, 0xbe, 0x37, 0x48, 0xca, 0x67, 0x30,
	0x4a, 0xa5, 0x50, 0x28, 0x14, 0xb3, 0x02, 0x2b, 0x9a, 0xf0, 0x5e, 0xfa, 0x3e, 0x38, 0x4d, 0x5d,
	0x10, 0x1b, 0x04, 0x76, 0x34, 0xe1, 0xfa, 0x1d, 0x7e, 0x5b, 0x30, 0x3f, 0x19, 0x43, 0x95, 0x14,
	0x84, 0xfe, 0x2d, 0x78, 0xa4, 0x12, 0xd5, 0x50, 0x9c, 0xca, 0x0c, 0xf5, 0x2c, 0x97, 0x83, 0xb1,
	0x96, 0x32, 0xc3, 0x76, 0x51, 0x47, 0xc4, 0x06, 0x66, 0x51, 0x27, 0xfd, 0x1b, 0x80, 0xee, 0x19,
	0x17, 0x19, 0xb3, 0x03, 0x2b, 0xb2, 0xf9, 0xa4, 0x73, 0x56, 0xd9, 0x31, 0xa1, 0x73, 0x99, 0xd0,
	0x3d, 0x10, 0xb6, 0x1c, 0xa9, 0x06, 0x8c, 0x55, 0x51, 0x22, 0x1b, 0xea, 0x69, 0x60, 0xac, 0x4d,
	0x51, 0x62, 0x98, 0xc3, 0xfc, 0x19, 0xd5, 0x0b, 0xee, 0xf2, 0x93, 0x26, 0x66, 0xe0, 0x16, 0x22,
	0xc3, 0x0f, 0xcd, 0x6e, 0x73, 0x23, 0x5a, 0x37, 0x95, 0x8d, 0x50, 0x1a, 0xda, 0xe6, 0x46, 0xf8,
	0x77, 0x30, 0xed, 0x91, 0xd5, 0xbe, 0x42, 0x0d, 0xed, 0x72, 0xaf, 0xf3, 0x36, 0xfb, 0x0a, 0xc3,
	0x4f, 0xf0, 0xba, 0x05, 0x2b, 0x91, 0xcb, 0x93, 0x90, 0xd6, 0x1f, 0x21, 0x07, 0x17, 0x42, 0xee,
	0x88, 0xd9, 0x7d, 0xc8, 0xdd, 0x59, 0x48, 0xe7, 0x2c, 0xe4, 0x97, 0x75, 0x9e, 0x92, 0xfe, 0xfb,
	0x4f, 0xf7, 0xbf, 0x37, 0x15, 0x17, 0x22, 0x97, 0x06, 0xc9, 0x7b, 0x98, 0x2e, 0x8e, 0x72, 0xf2,
	0xbe, 0x97, 0x56, 0xd0, 0xa1, 0x3d, 0xe7, 0xb8, 0xbd, 0x6b, 0x18, 0x6f, 0x13, 0x8a, 0x4b, 0x59,
	0x23, 0x73, 0x03, 0x2b, 0x1a, 0xf3, 0xd1, 0x36, 0xa1, 0xb5, 0xac, 0xf1, 0x75, 0xa8, 0xaf, 0xf5,
	0xf1, 0x27, 0x00, 0x00, 0xff, 0xff, 0x03, 0x8f, 0x03, 0x17, 0xbe, 0x02, 0x00, 0x00,
}
