// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        (unknown)
// source: digg.proto

package digg

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DiggType int32

const (
	DiggType_ZERO        DiggType = 0 //无意义
	DiggType_DIGG        DiggType = 1 //点赞
	DiggType_CANCAL_DIGG DiggType = 2 //取消点赞
)

// Enum value maps for DiggType.
var (
	DiggType_name = map[int32]string{
		0: "ZERO",
		1: "DIGG",
		2: "CANCAL_DIGG",
	}
	DiggType_value = map[string]int32{
		"ZERO":        0,
		"DIGG":        1,
		"CANCAL_DIGG": 2,
	}
)

func (x DiggType) Enum() *DiggType {
	p := new(DiggType)
	*p = x
	return p
}

func (x DiggType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiggType) Descriptor() protoreflect.EnumDescriptor {
	return file_digg_proto_enumTypes[0].Descriptor()
}

func (DiggType) Type() protoreflect.EnumType {
	return &file_digg_proto_enumTypes[0]
}

func (x DiggType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiggType.Descriptor instead.
func (DiggType) EnumDescriptor() ([]byte, []int) {
	return file_digg_proto_rawDescGZIP(), []int{0}
}

type ContentType int32

const (
	ContentType_ContentType_XX ContentType = 0 //无意义
	ContentType_MESSAGE        ContentType = 1 //帖子
	ContentType_SECOND_HAND    ContentType = 2 //二手市场
	ContentType_COMMENT        ContentType = 3 //评论
)

// Enum value maps for ContentType.
var (
	ContentType_name = map[int32]string{
		0: "ContentType_XX",
		1: "MESSAGE",
		2: "SECOND_HAND",
		3: "COMMENT",
	}
	ContentType_value = map[string]int32{
		"ContentType_XX": 0,
		"MESSAGE":        1,
		"SECOND_HAND":    2,
		"COMMENT":        3,
	}
)

func (x ContentType) Enum() *ContentType {
	p := new(ContentType)
	*p = x
	return p
}

func (x ContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_digg_proto_enumTypes[1].Descriptor()
}

func (ContentType) Type() protoreflect.EnumType {
	return &file_digg_proto_enumTypes[1]
}

func (x ContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentType.Descriptor instead.
func (ContentType) EnumDescriptor() ([]byte, []int) {
	return file_digg_proto_rawDescGZIP(), []int{1}
}

//点赞
//POST /digg
type DiggRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId int64    `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id"`            //点赞的消息id
	DiggType  DiggType `protobuf:"varint,2,opt,name=digg_type,json=diggType,proto3,enum=DiggType" json:"digg_type"` //点赞类型
}

func (x *DiggRequest) Reset() {
	*x = DiggRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_digg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiggRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiggRequest) ProtoMessage() {}

func (x *DiggRequest) ProtoReflect() protoreflect.Message {
	mi := &file_digg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiggRequest.ProtoReflect.Descriptor instead.
func (*DiggRequest) Descriptor() ([]byte, []int) {
	return file_digg_proto_rawDescGZIP(), []int{0}
}

func (x *DiggRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *DiggRequest) GetDiggType() DiggType {
	if x != nil {
		return x.DiggType
	}
	return DiggType_ZERO
}

type DiggResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code"` //状态码，0是成功，其它是错误码
	Message    string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`                          // 错误信息，0时为success
	DiggCount  int32  `protobuf:"varint,3,opt,name=digg_count,json=diggCount,proto3" json:"digg_count"`    // 当前点赞数
}

func (x *DiggResponse) Reset() {
	*x = DiggResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_digg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiggResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiggResponse) ProtoMessage() {}

func (x *DiggResponse) ProtoReflect() protoreflect.Message {
	mi := &file_digg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiggResponse.ProtoReflect.Descriptor instead.
func (*DiggResponse) Descriptor() ([]byte, []int) {
	return file_digg_proto_rawDescGZIP(), []int{1}
}

func (x *DiggResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DiggResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DiggResponse) GetDiggCount() int32 {
	if x != nil {
		return x.DiggCount
	}
	return 0
}

var File_digg_proto protoreflect.FileDescriptor

var file_digg_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x64, 0x69, 0x67, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x0b,
	0x44, 0x69, 0x67, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x09, 0x64, 0x69,
	0x67, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e,
	0x44, 0x69, 0x67, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x64, 0x69, 0x67, 0x67, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x68, 0x0a, 0x0c, 0x44, 0x69, 0x67, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x64, 0x69, 0x67, 0x67, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x64, 0x69, 0x67, 0x67, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x2a, 0x2f, 0x0a, 0x08,
	0x44, 0x69, 0x67, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x5a, 0x45, 0x52, 0x4f,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x49, 0x47, 0x47, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b,
	0x43, 0x41, 0x4e, 0x43, 0x41, 0x4c, 0x5f, 0x44, 0x49, 0x47, 0x47, 0x10, 0x02, 0x2a, 0x4c, 0x0a,
	0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x0e,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x58, 0x58, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x01, 0x12, 0x0f, 0x0a,
	0x0b, 0x53, 0x45, 0x43, 0x4f, 0x4e, 0x44, 0x5f, 0x48, 0x41, 0x4e, 0x44, 0x10, 0x02, 0x12, 0x0b,
	0x0a, 0x07, 0x43, 0x4f, 0x4d, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x03, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_digg_proto_rawDescOnce sync.Once
	file_digg_proto_rawDescData = file_digg_proto_rawDesc
)

func file_digg_proto_rawDescGZIP() []byte {
	file_digg_proto_rawDescOnce.Do(func() {
		file_digg_proto_rawDescData = protoimpl.X.CompressGZIP(file_digg_proto_rawDescData)
	})
	return file_digg_proto_rawDescData
}

var file_digg_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_digg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_digg_proto_goTypes = []interface{}{
	(DiggType)(0),        // 0: DiggType
	(ContentType)(0),     // 1: ContentType
	(*DiggRequest)(nil),  // 2: DiggRequest
	(*DiggResponse)(nil), // 3: DiggResponse
}
var file_digg_proto_depIdxs = []int32{
	0, // 0: DiggRequest.digg_type:type_name -> DiggType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_digg_proto_init() }
func file_digg_proto_init() {
	if File_digg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_digg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiggRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_digg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiggResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_digg_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_digg_proto_goTypes,
		DependencyIndexes: file_digg_proto_depIdxs,
		EnumInfos:         file_digg_proto_enumTypes,
		MessageInfos:      file_digg_proto_msgTypes,
	}.Build()
	File_digg_proto = out.File
	file_digg_proto_rawDesc = nil
	file_digg_proto_goTypes = nil
	file_digg_proto_depIdxs = nil
}
